# Generated by Django 5.0.6 on 2024-05-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangopress_posts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
