# Generated by Django 5.0.6 on 2024-06-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangopress_media", "0004_mediaasset_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="file_content_type",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="file_hash",
            field=models.CharField(default="", max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="file_size",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
