# Generated by Django 5.2.4 on 2025-08-03 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("djangopress_spaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="spaceuser",
            table="djangopress_spaceuser",
        ),
    ]
