services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      target: dev
    init: true
    command: django-admin runserver 0.0.0.0:8000
    environment:
      DJANGO_SECRET_KEY: secret
      DJANGO_DEBUG: "true"
      DEMO_MODE: "true"
      DJANGO_ALLOWED_HOSTS: "*"
      DATABASE_URL: postgres://postgres@postgres/postgres
      VITE_SERVER_ORIGIN: http://localhost:5173/static
    ports:
      - 8000:8000
    volumes:
      - ./server:/server/
      - ./client:/client/
    depends_on:
      postgres:
        condition: service_healthy

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
      target: dev
    init: true
    command: npm run dev -- --host
    volumes:
      - ./client:/client/
    ports:
      - 5173:5173

  postgres:
    image: postgres:17
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
