# Generated by Django 5.0.7 on 2025-03-21 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("djangopress", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebSite",
            fields=[
                (
                    "channel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="djangopress.channel",
                    ),
                ),
                ("domain_name", models.CharField(max_length=255)),
                ("base_path", models.CharField(blank=True, max_length=255)),
            ],
            bases=("djangopress.channel",),
        ),
    ]
