# Generated by Django 5.0.7 on 2025-05-31 23:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("djangopress_files", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blob",
            old_name="content_type",
            new_name="mime_type",
        ),
    ]
