# Generated by Django 5.0.7 on 2025-06-01 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("djangopress_content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="djangopress_content.content",
                    ),
                ),
                ("content", models.JSONField()),
            ],
            options={
                "db_table": "djangopress_page",
            },
            bases=("djangopress_content.content",),
        ),
    ]
