# Generated by Django 5.2.4 on 2025-08-03 17:03

import django.db.models.deletion
import uuid_extensions.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("djangopress_spaces", "0002_alter_spaceuser_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("version", models.PositiveIntegerField(default=1)),
                ("schema", models.JSONField()),
                ("migration_operations", models.JSONField(blank=True, null=True)),
                (
                    "migration_target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="djangopress_pages.pagecontenttype",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_content_types",
                        to="djangopress_spaces.space",
                    ),
                ),
            ],
            options={
                "db_table": "djangopress_pagecontenttype",
                "unique_together": {("space", "name", "version")},
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_extensions.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path", models.TextField()),
                ("content", models.JSONField()),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="djangopress_spaces.space",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="djangopress_pages.pagecontenttype",
                    ),
                ),
            ],
            options={
                "db_table": "djangopress_page",
                "unique_together": {("space", "path")},
            },
        ),
    ]
