# Generated by Django 5.2.4 on 2025-08-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangopress_pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="title",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
