# Generated by Django 5.0.6 on 2024-06-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangopress_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_temporary",
            field=models.BooleanField(default=False),
        ),
    ]
