# Generated by Django 5.0.7 on 2025-05-31 22:50

import django.db.models.deletion
import uuid_extensions
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("djangopress_spaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid_extensions.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        to="djangopress_spaces.space",
                    ),
                ),
            ],
            options={
                "db_table": "djangopress_content",
                "unique_together": {("space", "name")},
            },
        ),
    ]
